blog/urls.py
from django.urls import path, include, re_path
from . import views 

urlpatterns = [
	path('', views.index, name='home'),
	path('article/<int:article_id>/', views.article_page, name='article_page'),
	path('edit/<int:article_id>/', views.edit_page, name='edit_page'),
	path('edit_action/', views.edit_action, name='edit_action'),
	path('about_me/', views.about, name='about'),
    path('tag/', views.tag, name='tag'),
    path('tag/<str:tag>/', views.tag_articles, name='tag_articles')
]

comments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.comments, name='comments'),
    path('post_comment/', views.post_comment, name='post_comment'),
]

newsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    # include((pattern_list, app_namespace), namespace=None)
    # app_namespase:app名称 namespace: app实例名称
    # 模板里调用实例: {% url 'app_name:path_name' %}
	path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('register/', include(('users.urls', 'register'), namespace='register')),
    path('message_board/', include(('comments.urls', 'message_board'), namespace='comments')),
    path('image_rec/', include(('image_rec.urls', 'image_rec'), namespace='image_rec')),
]

# Debug 模式用的处理media视图函数, 生产模式要自己配置
# 配置处理media里的文件的路由
# serve视图函数:https://docs.djangoproject.com/en/2.1/ref/views/
from django.conf import settings
from django.urls import re_path
from django.views.static import serve


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class article(models.Model):
	def __str__(self):
		return self.title
	#相当于verbose_name
	# class Meta:
	# 	verbose_name = 'Ariticle'
	# 	verbose_name_plural = 'Ariticles'

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])


	title = models.CharField(max_length=20,null=True)
	content = models.TextField(null=True)
	pub_time = models.DateTimeField(auto_now=True)
	views = models.PositiveIntegerField(default=0)
	tag = models.CharField(max_length=20,null=True)
	author = models.CharField(max_length=20,default="sawyer")
	isTop = models.BooleanField(default=False)

	

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from . import models
import markdown

# Create your views here.
def index(request):
	articles = models.article.objects.order_by('pub_time').reverse()
	tags = set((article.tag for article in articles))
	few_texts = (article.content[:500] for article in articles)
	# 判断有没有置顶
	try:
		topArticle = models.article.objects.get(isTop=1)
	except Exception as e:
		return render(request, 'blog/index.html', {'zip': zip(articles, few_texts)})
	return render(request, 'blog/index.html', {'zip': zip(articles, few_texts), 'topArticle':topArticle})

def article_page(request, article_id=0):
# article = models.article.objects.get(pk=article_id)
# return render(request, 'blog/article_page.html', {'article':article})
	article = get_object_or_404(models.article, pk=article_id)
	article.increase_views()
	article.content = markdown.markdown(article.content,
		extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc',
		])
	return render(request, 'blog/article_page.html', context={'article': article})

def edit_action(request):
	title = request.POST.get('title', "TITLE")
	content = request.POST.get('content', "None")
	article_id = request.POST.get('article_id', '0')
	tag = request.POST.get('tag', 'None')

	if str(article_id) == '0':
		article = models.article.objects.create(title=title, content=content)
		article.save()
		return redirect('/article/' + str(article.id))

	else:
		article = models.article.objects.get(pk=article_id)
		article.title = title
		article.content = content
		article.tag = tag
		article.save()
		return redirect('/article/' + str(article.id))

def edit_page(request, article_id):
	if str(article_id) == '0':
		return render(request, 'blog/edit_page.html')
	else:
		article = models.article.objects.get(pk=article_id)
		return render(request, 'blog/edit_page.html', {'article':article})


def about(request):
	return render(request, 'blog/about.html')

def tag(request):
	articles = models.article.objects.all()
	tags = set((article.tag for article in articles))
	return render(request, 'blog/tag.html', {'tags': tags})

def tag_articles(request, tag='None'):
	articles = models.article.objects.filter(tag=tag)
	few_texts = (article.content[:20] for article in articles)
	return render(request, 'blog/tag_articles.html', {'zip': zip(articles, few_texts)})

blog/templates/blog/about.html
{% extends "blog/base.html" %}            

{% block stuff %}
    <h1>
        I am SAWYER..
        <br>
        This is mysite..
    </h1>
{% endblock %}



            

blog/templates/blog/article_page.html
{% extends 'blog/base.html' %}

{% block stuff %}

<section class="post">
    <header class="post-header">
        <h1 class="post-title">{{ article.title }}</h1>
        <p class="post-meta">Time:{{ article.pub_time }}<a class="post-category post-category-js" href="#">{{ article.tag }}</a></p>
        <p align="right" class="views-count">{{ article.views }} 阅读</a></p>
    </header>
    <div class="post-description">
        <p>{{ article.content|safe}}</p>
    </div>
</section>

<!-- #如果是超级管理员 -->
{% if user.username == 'admin' %}
<a href = "{% url 'blog:edit_page' article.id %}" class="button-secondary pure-button">修改文章</a>
{% endif %}
<br>
<h1><a href="/"><<< </a></h1>

{% endblock %}

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a blog page with a list of posts.">
    <title>Fsociety</title>
    <link rel="stylesheet" href="{% static 'blog/css/pure-min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/grids-responsive-min.css' %}">
    <link rel="static stylesheet" href="{% static 'blog/css/blog.css' %}">
    <style scoped>
        .button-success,
        .button-error,
        .button-warning,
        .button-secondary {
            color: white;
            border-radius: 4px;
            text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
        }

        .button-success {
            background: rgb(28, 184, 65); /* this is a green */
        }

        .button-error {
            background: rgb(202, 60, 60); /* this is a maroon */
        }

        .button-warning {
            background: rgb(223, 117, 20); /* this is an orange */
        }

        .button-secondary {
            background: rgb(66, 184, 221); /* this is a light blue */
        }

    </style>     
</head>

<body>
<script src="{% static 'blog/js/myScript.js' %}"></script>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <div  style="width: 74px; height: 74px;border-radius: 50%; border: 3px solid #eee; 
                        overflow: hidden;margin-left:auto;margin-right:auto;margin-bottom:20px;">    
                <img class="pure-img" src="{% static 'blog/img/a.jpg' %}" width="80" height="80" />
            </div>
            <h1 class="brand-title">sawyer's site</h1>
            <h2 class="brand-tagline">somthing cooooool...</h2>

            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:about' %}">About me</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:home' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'comments:comments' %}">MessageBoard</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:tag' %}">Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'blog:home' %}">Game</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="{% url 'image_rec:home' %}">Image recognize</a>
                    </li>
                    
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <div>
                <div>
                    <button class="button-success pure-button", onclick='saysomething(1)'>Button1</button>
                    <button class="button-error pure-button", onclick='saysomething(2)'>Button2</button>
                    <button class="button-warning pure-button", onclick='saysomething(3)'>Button3</button>
                    <button class="button-secondary pure-button", onclick='saysomething(4)'>Button4</button>
                </div>
                {% if user.is_authenticated %}
                <p>你已登录，欢迎你: {{ user.username }}<a class="button-error pure-button" href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                <a class="button-warning pure-button" href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></p>
                {% else%}
                <p>你还没有登录, 请登录...<a class="button-secondary pure-button" href="{% url 'login' %}?next={{ request.path }}">登录</a></p>
                {% endif %}
            </div>
            {% block stuff %}
            
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal">
                    <ul>
                        <li class="pure-menu-item"><a href="{% url 'blog:about' %}" class="pure-menu-link">About</a></li>
                        <li class="pure-menu-item"><a href="https://twitter.com/">Twitter</a></li>
                        <li class="pure-menu-item"><a href="https://github.com/sawyerRick">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/edit_page.html
{% extends 'blog/base.html' %}
{% block stuff %}


<div class="posts">
    <!-- A single blog post -->
    <section class="post">
        <form id = edit_page_form class="pure-form" action="{% url 'blog:edit_action' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <!-- 新增文章id默认为0 -->
                <!-- http post按照name=value传递参数 -->
                <input type="hidden"  name="article_id" value="{{ article.id | default:'0'}}">
                <input type="text" placeholder="输入题目..." autocomplete="off" name="title" value="{{ article.title }}">
                <br>
                <input type="text" placeholder="输入标签..." autocomplete="off" name="tag" value="{{ article.tag }}">
                <br>
                <textarea rows="10" placeholder="输入内容..." autocomplete="off" cols="100" name="content" form="edit_page_form">{{ article.content }}</textarea>
            </fieldset>
            <input class="pure-button pure-button-primary" type="submit" value="提交">
        </form>
    </section>
</div>


{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}
{% block stuff%}


{% if user.username == 'admin' %}
<br>
<a class="pure-button pure-button-primary" href="{% url 'blog:edit_page' 0 %}">新文章</a>
{% endif %}
{% if topArticle.title %}
<div class="posts">
    <h1 class="content-subhead">置顶</h1>
    <!-- A single blog post -->
    <header class="post-header">
        <h2 class="post-title">{{ topArticle.title | default:"None"}}</h2>
        <p class="post-meta">
            Time:{{ topArticle.pub_time }}<a class="post-category post-category-js" href="{% url 'blog:tag_articles' topArticle.tag %}">{{ topArticle.tag }}</a>
            <span class="post-count" style="float:right">{{ topArticle.views }} 阅读</span>
        </p>
        <p>{{ text }}...<br><h3><a href="{% url 'blog:article_page' topArticle.id %}">More</a><h3></p>
    </header>
</div>
{% endif %}
<!-- A single blog post -->
<h1 class="content-subhead">最近</h1>
{% for article, text in zip %}
<section class="post">
    <header class="post-header">
        <h2 class="post-title">{{ article.title | default:"None"}}</h2>
        <p class="post-meta">
            Time:{{ article.pub_time }}<a class="post-category post-category-js" href="{% url 'blog:tag_articles' article.tag %}">{{ article.tag }}</a>
            <span class="post-count" style="float:right">{{ article.views }} 阅读</span>
        </p>
        <p>{{ text }}...<br><h3><a href="{% url 'blog:article_page' article.id %}">More</a><h3></p>
    </header>
</section>
{% endfor %}


{% endblock %}

blog/templates/blog/tag.html
{% extends 'blog/base.html' %}

{% block stuff %}

{% for tag in tags %}
    <section class="post">
        <header class="post-header">
            <p class="post-meta"><a class="post-category post-category-js" href="{% url 'blog:tag_articles' tag %}">{{ tag }}</a>
            </p>
        </header>
    </section>
{% endfor %}

{% endblock %}

blog/templates/blog/tag_articles.html
{% extends 'blog/base.html' %}

{% block stuff %}

{% for article, text in zip %}
<section class="post">
    <header class="post-header">
        <h1 class="post-title">{{ article.title | default:"None"}}</a></h1>
        <p class="post-meta">
            Time:{{ article.pub_time }}<a class="post-category post-category-js">{{ article.tag }}</a>
            <span class="post-count" style="float:right">{{ article.views }} 阅读</span>
        </p>
        <p>{{ text }}...<br><h3><a href="{% url 'blog:article_page' article.id %}">More</a><h3></p>
    </header>
</section>
{% endfor %}

{% endblock %}