blog/urls.py
from django.urls import path, include, re_path
from . import views 

urlpatterns = [
	path('', views.index, name='home'),
	path('article/<int:article_id>/', views.article_page, name='article_page'),
	path('edit/<int:article_id>/', views.edit_page, name='edit_page'),
	path('edit_action/', views.edit_action, name='edit_action'),
	path('about_me/', views.about, name='about'),
    path('tag/', views.tag, name='tag'),
    path('tag/<str:tag>/', views.tag_articles, name='tag_articles')
]

newsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    # include((pattern_list, app_namespace), namespace=None)
    # app_namespase:app名称 namespace: app实例名称
    # 模板里调用实例: {% url 'app_name:path_name' %}
	path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('register/', include(('users.urls', 'register'), namespace='register')),
    path('message_board/', include(('comments.urls', 'message_board'), namespace='comments')),
    path('image_rec/', include(('image_rec.urls', 'image_rec'), namespace='image_rec')),
]

# Debug 模式用的处理media视图函数, 生产模式要自己配置
# 配置处理media里的文件的路由
# serve视图函数:https://docs.djangoproject.com/en/2.1/ref/views/
from django.conf import settings
from django.urls import re_path
from django.views.static import serve


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

users/urls.py
from django.urls import path
from . import views 

urlpatterns = [
	path('', views.register, name='registe'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from . import models

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = ("username", "email")

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.http import HttpResponse

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})

def index(request):
    return render(request, 'index.html')

users/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="{% static 'users/css/mobi.css' %}">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'register:registe' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>